### ISSUE TITLE
We are best friends

### ISSUE THREAD

**Issue by ScottyEfird** [UWYO-Fall15-Sr-Design-Drone/CoscSrDesignDrones#1]
<3

**Comment by samin17** [comment]
We should be fine if we practice enough tonight.

**Comment by jakestreett** [comment]
You meant to say Sam "With all the practice we have been going through all week, we will be fine", right?

**Comment by ScottEfird** [comment]
I'll I'm saying is that we sacrifice a goat in the name of Muhammad (praise be unto him) just to be safe. I think the pet store downtown sells one.

**Comment by samin17** [comment]
Why don't we ask one of the Arabs in class and "borrow" one of theirs?
